[phases.setup]
nixPkgs = ['go']

[phases.install]
cmds = ['go mod download']

[phases.build]
cmds = [
    'go build -o CUREXAL ./cmd/CUREXAL',
    'go build -o cron ./cmd/cron'
]

[start]
cmd = './CUREXAL'

[variables]
GO111MODULE = 'on'
CGO_ENABLED = '0'