[phases.setup]
nixPkgs = ['go']

[phases.install]
cmds = ['go mod download']

[phases.build]
cmds = [
    'go build -ldflags="-w -s" -o bin/curexal-backend ./cmd/CUREXAL'
]

[start]
cmd = './bin/curexal-backend'

[variables]
GO111MODULE = 'on'
CGO_ENABLED = '0'